(define (create-underwater name)
	(let*
		(
			(image (car (gimp-image-new 460 360 RGB)))
			(water (car (gimp-layer-new image 460 360 RGB-IMAGE "Water" 100 NORMAL-MODE)))
		)
		(gimp-image-insert-layer image water 0 0)
		(gimp-drawable-fill water WHITE-FILL)
		(script-fu-lava image water 10 10 7 "Horizon 2" FALSE FALSE FALSE)
		(script-fu-tile-blur image water 16 TRUE TRUE 0)
		(gimp-context-set-foreground '(255 255 255))
		(gimp-edit-blend water FG-TRANSPARENT-MODE NORMAL-MODE GRADIENT-LINEAR 100 0 REPEAT-NONE FALSE FALSE 1 0 TRUE 0 0 0 360)
		(file-jpeg-save RUN-NONINTERACTIVE image (car (gimp-image-flatten image)) name name 0.7 0 TRUE TRUE "" 2 1 0 0)
		(gimp-image-delete image)
	)
)
